@startuml packages_casonk.github.io
set namespaceSeparator none
top to bottom direction
skinparam componentStyle rectangle
rectangle "scripts.extract_education\n1 python file" as scripts.extract_education
rectangle "talkmap\n1 python file" as talkmap
@enduml
